Neos:
  Flow:
    log:
      psr3:
        'Neos\Flow\Log\PsrLoggerFactory':
          'Carbon.Plaintext:PlaintextLogger':
            default:
              options:
                severityThreshold: '%LOG_INFO%'
