Neos:
  Neos:
    fusion:
      autoInclude:
        'Carbon.Plaintext': true
  Fusion:
    defaultContext:
      'Carbon.Plaintext': 'Carbon\Plaintext\Eel\PlaintextHelper'
  Flow:
    mvc:
      routes:
        'Carbon.Plaintext':
          position: 'start'
    log:
      psr3:
        'Neos\Flow\Log\PsrLoggerFactory':
          'Carbon.Plaintext:PlaintextLogger':
            default:
              class: Neos\Flow\Log\Backend\FileBackend
              options:
                logFileURL: '%FLOW_PATH_DATA%Logs/Plaintext.log'
                createParentDirectories: true
                severityThreshold: '%LOG_DEBUG%'
                maximumLogFileSize: 10485760
                logFilesToKeep: 1
